import Head from 'next/head'
import './globals.css'
import ProductProvider from '@/providers/ProductProvider'


export const metadata = {
  title: 'Amazon Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ProductProvider>

        {children}

        </ProductProvider>
      
      </body>
    </html>
  )
}
