import './globals.css'
import ProductProvider from '@/providers/ProductProvider'
import CategoryNavbar from '@/components/category_navbar/CategoryNavbar'
import Navbar from '@/components/navbar/Navbar'
import CartProvider from '@/providers/CartProvider'
import { Toaster } from 'react-hot-toast'


export const metadata = {
  title: 'Amazon Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className=''>
        <CartProvider>
        <ProductProvider>
        <Navbar/>
        <CategoryNavbar/>
        <Toaster/>
        {children}

        </ProductProvider>
        </CartProvider>
      
      </body>
    </html>
  )
}
