import Head from 'next/head'
import './globals.css'


export const metadata = {
  title: 'Amazon Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <link rel="shortcut icon" href="i" type="image/x-icon" /> */}
        <title>Hello</title>
      </Head>
      <body>{children}</body>
    </html>
  )
}
